### ISSUE TITLE
Supplementary materials missing

### ISSUE THREAD

**Issue by MingwuZheng** [microsoft/DIF-Net#1]
Hi, can you upload the supplementary materials together?

**Comment by YuDeng** [comment]
Hi, please check our (Arxiv version)[https://arxiv.org/abs/2011.13650] which includes the supplementary materials.

**Comment by MingwuZheng** [comment]
> Hi, please check our [Arxiv version](https://arxiv.org/abs/2011.13650) which includes the supplementary materials.

I see it, thank you :)
